---
language: node_js
node_js:
- '4'
- '6'
- '7'
- '8'
install: true
env:
- EXAMPLE_PATH=./todo MODERN=1
- EXAMPLE_PATH=./todomvc-react-native
matrix:
  exclude:
    - node_js: '4'
      env: EXAMPLE_PATH=./todo MODERN=1
before_install: >
  (git clone git://github.com/facebook/watchman.git && \
    cd watchman && \
    git checkout v4.7.0 && \
    sudo apt-get install -y autoconf automake build-essential python-dev && \
    ./autogen.sh && \
    ./configure && \
    make && \
    sudo make install)
before_script:
  (cd $EXAMPLE_PATH && npm install)
script:
  (cd $EXAMPLE_PATH && npm run update-schema && { if [ -n "$MODERN" ]; then npm run build; fi })
